user authentication
fisufba/fisufba-server pull request #16
Opened 2019-05-14 03:39 UTC by helwohs

closes #1 
closes #2 
closes #7 
closes #14

2019-05-15 22:38 UTC, thelink2012 requested changes

2019-05-15 22:38 UTC, thelink2012 commented on api/auth.py
> +class _Signup(AppResource):
Troca pra um POST em /accounts

2019-05-15 22:38 UTC, thelink2012 commented on api/auth.py
> +        #  TODO check if the user has privileges to create another user
Resolver esse TODO

2019-05-15 22:38 UTC, thelink2012 commented on api/auth.py
> +
Talvez seja útil retornar o id do usuário que foi logado? Por exemplo, se o front quiser saber as informações do usuário logado, ele já tem o id e dai só dar um GET relacionado ao id, etc.

2019-05-15 22:38 UTC, thelink2012 commented on api/main.py
> +    Exception
O que é essa linha?

2019-05-16 18:24 UTC, helwohs commented on api/auth.py
> +
Irei editar

2019-05-16 18:24 UTC, helwohs commented on api/auth.py
> +        #  TODO check if the user has privileges to create another user
Já em andamento

2019-05-16 18:26 UTC, helwohs commented on api/main.py
> +    Exception
Erro meu, obrigado por reparar

2019-05-17 06:36 UTC, helwohs commented on api/auth.py
> +
ok

2019-05-17 07:53 UTC, helwohs commented on api/auth.py
> +        #  TODO check if the user has privileges to create another user
Apenas no próximo merge :/

2019-05-17 07:54 UTC, helwohs commented
Infelizmente não temos testes ainda, mas pretendo fazê-los assim que terminar os decorators e permissões (irá alterar as linhas iniciais de logout vide comentários).

2019-05-17 22:44 UTC, thelink2012 approved these changes

2019-05-17 23:02 UTC, merged