Dockerfile
fisufba/fisufba-server pull request #24
Opened 2019-05-17 23:38 UTC by thelink2012

Closes #15

2019-05-18 01:57 UTC, tysm requested changes

2019-05-18 01:57 UTC, helwohs commented on README.md
> +For deployment purposes, you need Docker and PostgreSQL only. Make sure you have a `fisufba` table already created in PostgreSQL.
table -> database;
(opcional) o nome pode ser qualquer um, desde que especificado em env.ini;

2019-05-18 01:57 UTC, helwohs commented on README.md
> +$ docker build -t fisufba-server .
o usuário terá acesso livre ao docker ou precisará de sudo?

2019-05-18 01:57 UTC, helwohs commented on README.md
> +$ docker build -t fisufba-server .
o mesmo vale para todas as ocorrências de docker

2019-05-18 01:57 UTC, helwohs commented on README.md
>  ### Testing
seria apenas no desenvolvimento, não?

2019-05-18 01:57 UTC, helwohs commented on .dockerignore
> +.venv
existe .venv mesmo utilizando pipenv? (só uma dúvida, não precisa remover)

2019-05-18 03:17 UTC, thelink2012 commented on README.md
> +$ docker build -t fisufba-server .
Se tiver no grupo `docker` (o que quase sempre é verdade) dá pra usar direto.

2019-05-18 03:17 UTC, thelink2012 commented on README.md
>  ### Testing
É uma seção sobre deployment em produção, então é bom não deixar o container na mesma network do host etc.

2019-05-18 03:18 UTC, thelink2012 commented on .dockerignore
> +.venv
Depende de uma variavel de ambiente (que eu pessoalmente uso no meu `.profile`) chamada `PIPENV_VENV_IN_PROJECT`.

2019-05-19 21:18 UTC, helwohs commented on README.md
>  ### Testing
tava falando de ### Testing

2019-05-19 21:19 UTC, tysm approved these changes

2019-05-19 21:19 UTC, thelink2012 commented on README.md
>  ### Testing
Mas isso é outra seção, não tem a ver com a de cima.

2019-05-23 18:49 UTC, merged